/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationAuditRouteImport } from './routes/validation-audit'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResultEntryRouteImport } from './routes/result-entry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentRegisterRouteImport } from './routes/student.register'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCarryoversRouteImport } from './routes/student.carryovers'
import { Route as FacultyTranscriptsRouteImport } from './routes/faculty.transcripts'
import { Route as FacultyStudentsRouteImport } from './routes/faculty.students'
import { Route as FacultyResultsRouteImport } from './routes/faculty.results'
import { Route as FacultyResultEntryRouteImport } from './routes/faculty.result-entry'
import { Route as FacultyLoginRouteImport } from './routes/faculty.login'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultyCoursesRouteImport } from './routes/faculty.courses'
import { Route as AdminFacultyAdminsRouteImport } from './routes/admin.faculty-admins'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const ValidationAuditRoute = ValidationAuditRouteImport.update({
  id: '/validation-audit',
  path: '/validation-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultEntryRoute = ResultEntryRouteImport.update({
  id: '/result-entry',
  path: '/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCarryoversRoute = StudentCarryoversRouteImport.update({
  id: '/student/carryovers',
  path: '/student/carryovers',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyTranscriptsRoute = FacultyTranscriptsRouteImport.update({
  id: '/faculty/transcripts',
  path: '/faculty/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyStudentsRoute = FacultyStudentsRouteImport.update({
  id: '/faculty/students',
  path: '/faculty/students',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyResultsRoute = FacultyResultsRouteImport.update({
  id: '/faculty/results',
  path: '/faculty/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyResultEntryRoute = FacultyResultEntryRouteImport.update({
  id: '/faculty/result-entry',
  path: '/faculty/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/faculty/login',
  path: '/faculty/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCoursesRoute = FacultyCoursesRouteImport.update({
  id: '/faculty/courses',
  path: '/faculty/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultyAdminsRoute = AdminFacultyAdminsRouteImport.update({
  id: '/admin/faculty-admins',
  path: '/admin/faculty-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/result-entry'
    | '/results'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/login'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/student/carryovers'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/student/register'
    | '/student/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/result-entry'
    | '/results'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/login'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/student/carryovers'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/student/register'
    | '/student/results'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/result-entry'
    | '/results'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/login'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/student/carryovers'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/student/register'
    | '/student/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResultEntryRoute: typeof ResultEntryRoute
  ResultsRoute: typeof ResultsRoute
  SessionsRoute: typeof SessionsRoute
  StudentsRoute: typeof StudentsRoute
  TranscriptsRoute: typeof TranscriptsRoute
  ValidationAuditRoute: typeof ValidationAuditRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminFacultyAdminsRoute: typeof AdminFacultyAdminsRoute
  FacultyCoursesRoute: typeof FacultyCoursesRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyLoginRoute: typeof FacultyLoginRoute
  FacultyResultEntryRoute: typeof FacultyResultEntryRoute
  FacultyResultsRoute: typeof FacultyResultsRoute
  FacultyStudentsRoute: typeof FacultyStudentsRoute
  FacultyTranscriptsRoute: typeof FacultyTranscriptsRoute
  StudentCarryoversRoute: typeof StudentCarryoversRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  StudentResultsRoute: typeof StudentResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-audit': {
      id: '/validation-audit'
      path: '/validation-audit'
      fullPath: '/validation-audit'
      preLoaderRoute: typeof ValidationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-entry': {
      id: '/result-entry'
      path: '/result-entry'
      fullPath: '/result-entry'
      preLoaderRoute: typeof ResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/carryovers': {
      id: '/student/carryovers'
      path: '/student/carryovers'
      fullPath: '/student/carryovers'
      preLoaderRoute: typeof StudentCarryoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/transcripts': {
      id: '/faculty/transcripts'
      path: '/faculty/transcripts'
      fullPath: '/faculty/transcripts'
      preLoaderRoute: typeof FacultyTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/students': {
      id: '/faculty/students'
      path: '/faculty/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof FacultyStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/results': {
      id: '/faculty/results'
      path: '/faculty/results'
      fullPath: '/faculty/results'
      preLoaderRoute: typeof FacultyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/result-entry': {
      id: '/faculty/result-entry'
      path: '/faculty/result-entry'
      fullPath: '/faculty/result-entry'
      preLoaderRoute: typeof FacultyResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/login': {
      id: '/faculty/login'
      path: '/faculty/login'
      fullPath: '/faculty/login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/courses': {
      id: '/faculty/courses'
      path: '/faculty/courses'
      fullPath: '/faculty/courses'
      preLoaderRoute: typeof FacultyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculty-admins': {
      id: '/admin/faculty-admins'
      path: '/admin/faculty-admins'
      fullPath: '/admin/faculty-admins'
      preLoaderRoute: typeof AdminFacultyAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResultEntryRoute: ResultEntryRoute,
  ResultsRoute: ResultsRoute,
  SessionsRoute: SessionsRoute,
  StudentsRoute: StudentsRoute,
  TranscriptsRoute: TranscriptsRoute,
  ValidationAuditRoute: ValidationAuditRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminFacultyAdminsRoute: AdminFacultyAdminsRoute,
  FacultyCoursesRoute: FacultyCoursesRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyLoginRoute: FacultyLoginRoute,
  FacultyResultEntryRoute: FacultyResultEntryRoute,
  FacultyResultsRoute: FacultyResultsRoute,
  FacultyStudentsRoute: FacultyStudentsRoute,
  FacultyTranscriptsRoute: FacultyTranscriptsRoute,
  StudentCarryoversRoute: StudentCarryoversRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  StudentResultsRoute: StudentResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
