/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationAuditRouteImport } from './routes/validation-audit'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResultEntryRouteImport } from './routes/result-entry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'

const ValidationAuditRoute = ValidationAuditRouteImport.update({
  id: '/validation-audit',
  path: '/validation-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultEntryRoute = ResultEntryRouteImport.update({
  id: '/result-entry',
  path: '/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/result-entry'
    | '/results'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/result-entry'
    | '/results'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/result-entry'
    | '/results'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResultEntryRoute: typeof ResultEntryRoute
  ResultsRoute: typeof ResultsRoute
  SessionsRoute: typeof SessionsRoute
  StudentsRoute: typeof StudentsRoute
  TranscriptsRoute: typeof TranscriptsRoute
  ValidationAuditRoute: typeof ValidationAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-audit': {
      id: '/validation-audit'
      path: '/validation-audit'
      fullPath: '/validation-audit'
      preLoaderRoute: typeof ValidationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-entry': {
      id: '/result-entry'
      path: '/result-entry'
      fullPath: '/result-entry'
      preLoaderRoute: typeof ResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResultEntryRoute: ResultEntryRoute,
  ResultsRoute: ResultsRoute,
  SessionsRoute: SessionsRoute,
  StudentsRoute: StudentsRoute,
  TranscriptsRoute: TranscriptsRoute,
  ValidationAuditRoute: ValidationAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
